version: '3'

services:

  email-service:
    image: ghcr.io/pht-medic/central-email-service:latest
    container_name: email-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SMTP_USER=
      - SMTP_PASSWORD=
      - UI_USER=
      - UI_TOKEN=
      - UI_ADDRESS=
      - SMTP_MAIL_FROM=
      - SMTP_HOST=

  train-router:
    image: ghcr.io/pht-medic/train-router:dev
    container_name: train-router
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis

  train-builder:
    container_name: train-builder
    image: ghcr.io/pht-medic/train-builder:dev
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
    restart: unless-stopped
