version: '3'

services:
  vault:
    image: vault:latest
    container_name: pht-vault
    restart: unless-stopped
    volumes:
      - ./vault/config:/vault/config
      - ./vault/file:/vault/file
      - ./vault/logs:/vault/logs
    ports:
      - "3400:3400"
    environment:
      - VAULT_ADDR=http://0.0.0.0:3400
      - VAULT_API_ADDR=http://0.0.0.0:3400
      - VAULT_ADDRESS=http://0.0.0.0:3400
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault_config.json

  email-service:
    image: registry.gitlab.com/personalhealthtrain/implementations/germanmii/difuture/central/email-service
    container_name: email-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SMTP_USER=
      - SMTP_PASSWORD=
      - UI_USER=
      - UI_TOKEN=
      - UI_ADDRESS=
      - SMTP_MAIL_FROM=
      - SMTP_HOST=

  train-router:
    image: registry.gitlab.com/personalhealthtrain/implementations/germanmii/difuture/central/train-router
    container_name: train-router
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis

  train-builder:
    container_name: train-builder
    image: registry.gitlab.com/personalhealthtrain/implementations/germanmii/difuture/central/train-builder
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"
